server:
  port: 10001
spring:
  application:
    name: station-server
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/station?characterEncoding=UTF-8&useTimeZone=GMT&useSSL=false
    username: root
    password: 123456
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
